// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aside.proto

package aside_pb

import (
	fmt "fmt"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Reason int32

const (
	Reason_SUCCESS             Reason = 100
	Reason_RAN_OUT_STUN_SERVER Reason = 201
	Reason_RAN_OUT_OF_RETRIES  Reason = 202
	Reason_PRIVATE_IP_STUN     Reason = 203
	Reason_MALFORMED_MESSAGE   Reason = 400
	Reason_UNKOWN_ERROR        Reason = 401
)

var Reason_name = map[int32]string{
	100: "SUCCESS",
	201: "RAN_OUT_STUN_SERVER",
	202: "RAN_OUT_OF_RETRIES",
	203: "PRIVATE_IP_STUN",
	400: "MALFORMED_MESSAGE",
	401: "UNKOWN_ERROR",
}

var Reason_value = map[string]int32{
	"SUCCESS":             100,
	"RAN_OUT_STUN_SERVER": 201,
	"RAN_OUT_OF_RETRIES":  202,
	"PRIVATE_IP_STUN":     203,
	"MALFORMED_MESSAGE":   400,
	"UNKOWN_ERROR":        401,
}

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return proto.EnumName(Reason_name, int32(x))
}

func (x *Reason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Reason_value, data, "Reason")
	if err != nil {
		return err
	}
	*x = Reason(value)
	return nil
}

func (Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{0}
}

type Hello struct {
	ShareStun     *bool `protobuf:"varint,1,req,name=shareStun" json:"shareStun,omitempty"`
	ShareGoodStun *bool `protobuf:"varint,2,req,name=shareGoodStun" json:"shareGoodStun,omitempty"`
	NeedStun      *bool `protobuf:"varint,3,req,name=needStun" json:"needStun,omitempty"`
	// Want stun explicitely ask for unkown status STUN.
	WantStun *bool `protobuf:"varint,4,req,name=wantStun" json:"wantStun,omitempty"`
	// Want good stun explicitely ask for good known STUN.
	WantGoodStun         *bool    `protobuf:"varint,5,req,name=wantGoodStun" json:"wantGoodStun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{0}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return m.Size()
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetShareStun() bool {
	if m != nil && m.ShareStun != nil {
		return *m.ShareStun
	}
	return false
}

func (m *Hello) GetShareGoodStun() bool {
	if m != nil && m.ShareGoodStun != nil {
		return *m.ShareGoodStun
	}
	return false
}

func (m *Hello) GetNeedStun() bool {
	if m != nil && m.NeedStun != nil {
		return *m.NeedStun
	}
	return false
}

func (m *Hello) GetWantStun() bool {
	if m != nil && m.WantStun != nil {
		return *m.WantStun
	}
	return false
}

func (m *Hello) GetWantGoodStun() bool {
	if m != nil && m.WantGoodStun != nil {
		return *m.WantGoodStun
	}
	return false
}

// Stun Server is a message used to be nested as list.
type StunServer struct {
	// Without `stun:`
	Domain               *string  `protobuf:"bytes,1,req,name=domain" json:"domain,omitempty"`
	Port                 *uint32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	KnownGood            *bool    `protobuf:"varint,3,req,name=knownGood" json:"knownGood,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StunServer) Reset()         { *m = StunServer{} }
func (m *StunServer) String() string { return proto.CompactTextString(m) }
func (*StunServer) ProtoMessage()    {}
func (*StunServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{1}
}
func (m *StunServer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StunServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StunServer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StunServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StunServer.Merge(m, src)
}
func (m *StunServer) XXX_Size() int {
	return m.Size()
}
func (m *StunServer) XXX_DiscardUnknown() {
	xxx_messageInfo_StunServer.DiscardUnknown(m)
}

var xxx_messageInfo_StunServer proto.InternalMessageInfo

func (m *StunServer) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *StunServer) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *StunServer) GetKnownGood() bool {
	if m != nil && m.KnownGood != nil {
		return *m.KnownGood
	}
	return false
}

type StunShare struct {
	StunServers          []*StunServer `protobuf:"bytes,1,rep,name=stunServers" json:"stunServers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StunShare) Reset()         { *m = StunShare{} }
func (m *StunShare) String() string { return proto.CompactTextString(m) }
func (*StunShare) ProtoMessage()    {}
func (*StunShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{2}
}
func (m *StunShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StunShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StunShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StunShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StunShare.Merge(m, src)
}
func (m *StunShare) XXX_Size() int {
	return m.Size()
}
func (m *StunShare) XXX_DiscardUnknown() {
	xxx_messageInfo_StunShare.DiscardUnknown(m)
}

var xxx_messageInfo_StunShare proto.InternalMessageInfo

func (m *StunShare) GetStunServers() []*StunServer {
	if m != nil {
		return m.StunServers
	}
	return nil
}

// SDP exchange, assume offer if sended by the initiator and reverse.
type SDP struct {
	Sdp                  *string  `protobuf:"bytes,1,req,name=sdp" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}
func (*SDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{3}
}
func (m *SDP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SDP.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDP.Merge(m, src)
}
func (m *SDP) XXX_Size() int {
	return m.Size()
}
func (m *SDP) XXX_DiscardUnknown() {
	xxx_messageInfo_SDP.DiscardUnknown(m)
}

var xxx_messageInfo_SDP proto.InternalMessageInfo

func (m *SDP) GetSdp() string {
	if m != nil && m.Sdp != nil {
		return *m.Sdp
	}
	return ""
}

type Candidate struct {
	Ice                  *string  `protobuf:"bytes,1,req,name=ice" json:"ice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{4}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return m.Size()
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetIce() string {
	if m != nil && m.Ice != nil {
		return *m.Ice
	}
	return ""
}

type GenerationEnded struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerationEnded) Reset()         { *m = GenerationEnded{} }
func (m *GenerationEnded) String() string { return proto.CompactTextString(m) }
func (*GenerationEnded) ProtoMessage()    {}
func (*GenerationEnded) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{5}
}
func (m *GenerationEnded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerationEnded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerationEnded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerationEnded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationEnded.Merge(m, src)
}
func (m *GenerationEnded) XXX_Size() int {
	return m.Size()
}
func (m *GenerationEnded) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationEnded.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationEnded proto.InternalMessageInfo

type AnswerTestingEnded struct {
	MoreStun             *bool    `protobuf:"varint,1,req,name=moreStun" json:"moreStun,omitempty"`
	MoreGoodStun         *bool    `protobuf:"varint,2,req,name=moreGoodStun" json:"moreGoodStun,omitempty"`
	Retry                *bool    `protobuf:"varint,3,req,name=retry" json:"retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerTestingEnded) Reset()         { *m = AnswerTestingEnded{} }
func (m *AnswerTestingEnded) String() string { return proto.CompactTextString(m) }
func (*AnswerTestingEnded) ProtoMessage()    {}
func (*AnswerTestingEnded) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{6}
}
func (m *AnswerTestingEnded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AnswerTestingEnded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AnswerTestingEnded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AnswerTestingEnded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerTestingEnded.Merge(m, src)
}
func (m *AnswerTestingEnded) XXX_Size() int {
	return m.Size()
}
func (m *AnswerTestingEnded) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerTestingEnded.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerTestingEnded proto.InternalMessageInfo

func (m *AnswerTestingEnded) GetMoreStun() bool {
	if m != nil && m.MoreStun != nil {
		return *m.MoreStun
	}
	return false
}

func (m *AnswerTestingEnded) GetMoreGoodStun() bool {
	if m != nil && m.MoreGoodStun != nil {
		return *m.MoreGoodStun
	}
	return false
}

func (m *AnswerTestingEnded) GetRetry() bool {
	if m != nil && m.Retry != nil {
		return *m.Retry
	}
	return false
}

type AcceptRetry struct {
	MoreStun             *bool    `protobuf:"varint,1,req,name=moreStun" json:"moreStun,omitempty"`
	MoreGoodStun         *bool    `protobuf:"varint,2,req,name=moreGoodStun" json:"moreGoodStun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptRetry) Reset()         { *m = AcceptRetry{} }
func (m *AcceptRetry) String() string { return proto.CompactTextString(m) }
func (*AcceptRetry) ProtoMessage()    {}
func (*AcceptRetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{7}
}
func (m *AcceptRetry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AcceptRetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AcceptRetry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AcceptRetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRetry.Merge(m, src)
}
func (m *AcceptRetry) XXX_Size() int {
	return m.Size()
}
func (m *AcceptRetry) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRetry.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRetry proto.InternalMessageInfo

func (m *AcceptRetry) GetMoreStun() bool {
	if m != nil && m.MoreStun != nil {
		return *m.MoreStun
	}
	return false
}

func (m *AcceptRetry) GetMoreGoodStun() bool {
	if m != nil && m.MoreGoodStun != nil {
		return *m.MoreGoodStun
	}
	return false
}

// Except if closing with SUCCESS an implementation may terminate violently (not sending Terminate message).
type Terminate struct {
	Reason               *Reason  `protobuf:"varint,1,req,name=reason,enum=aside.pb.Reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Terminate) Reset()         { *m = Terminate{} }
func (m *Terminate) String() string { return proto.CompactTextString(m) }
func (*Terminate) ProtoMessage()    {}
func (*Terminate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{8}
}
func (m *Terminate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Terminate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Terminate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Terminate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Terminate.Merge(m, src)
}
func (m *Terminate) XXX_Size() int {
	return m.Size()
}
func (m *Terminate) XXX_DiscardUnknown() {
	xxx_messageInfo_Terminate.DiscardUnknown(m)
}

var xxx_messageInfo_Terminate proto.InternalMessageInfo

func (m *Terminate) GetReason() Reason {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return Reason_SUCCESS
}

type WrapExchange struct {
	// Types that are valid to be assigned to M:
	//	*WrapExchange_Terminate
	//	*WrapExchange_Ice
	//	*WrapExchange_Genend
	M                    isWrapExchange_M `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WrapExchange) Reset()         { *m = WrapExchange{} }
func (m *WrapExchange) String() string { return proto.CompactTextString(m) }
func (*WrapExchange) ProtoMessage()    {}
func (*WrapExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{9}
}
func (m *WrapExchange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WrapExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WrapExchange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WrapExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapExchange.Merge(m, src)
}
func (m *WrapExchange) XXX_Size() int {
	return m.Size()
}
func (m *WrapExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapExchange.DiscardUnknown(m)
}

var xxx_messageInfo_WrapExchange proto.InternalMessageInfo

type isWrapExchange_M interface {
	isWrapExchange_M()
	MarshalTo([]byte) (int, error)
	Size() int
}

type WrapExchange_Terminate struct {
	Terminate *Terminate `protobuf:"bytes,1,opt,name=terminate,oneof" json:"terminate,omitempty"`
}
type WrapExchange_Ice struct {
	Ice *Candidate `protobuf:"bytes,2,opt,name=ice,oneof" json:"ice,omitempty"`
}
type WrapExchange_Genend struct {
	Genend *GenerationEnded `protobuf:"bytes,3,opt,name=genend,oneof" json:"genend,omitempty"`
}

func (*WrapExchange_Terminate) isWrapExchange_M() {}
func (*WrapExchange_Ice) isWrapExchange_M()       {}
func (*WrapExchange_Genend) isWrapExchange_M()    {}

func (m *WrapExchange) GetM() isWrapExchange_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *WrapExchange) GetTerminate() *Terminate {
	if x, ok := m.GetM().(*WrapExchange_Terminate); ok {
		return x.Terminate
	}
	return nil
}

func (m *WrapExchange) GetIce() *Candidate {
	if x, ok := m.GetM().(*WrapExchange_Ice); ok {
		return x.Ice
	}
	return nil
}

func (m *WrapExchange) GetGenend() *GenerationEnded {
	if x, ok := m.GetM().(*WrapExchange_Genend); ok {
		return x.Genend
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WrapExchange) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WrapExchange_Terminate)(nil),
		(*WrapExchange_Ice)(nil),
		(*WrapExchange_Genend)(nil),
	}
}

type WrapAnswerEnd struct {
	// Types that are valid to be assigned to M:
	//	*WrapAnswerEnd_Terminate
	//	*WrapAnswerEnd_Answerend
	M                    isWrapAnswerEnd_M `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WrapAnswerEnd) Reset()         { *m = WrapAnswerEnd{} }
func (m *WrapAnswerEnd) String() string { return proto.CompactTextString(m) }
func (*WrapAnswerEnd) ProtoMessage()    {}
func (*WrapAnswerEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{10}
}
func (m *WrapAnswerEnd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WrapAnswerEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WrapAnswerEnd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WrapAnswerEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapAnswerEnd.Merge(m, src)
}
func (m *WrapAnswerEnd) XXX_Size() int {
	return m.Size()
}
func (m *WrapAnswerEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapAnswerEnd.DiscardUnknown(m)
}

var xxx_messageInfo_WrapAnswerEnd proto.InternalMessageInfo

type isWrapAnswerEnd_M interface {
	isWrapAnswerEnd_M()
	MarshalTo([]byte) (int, error)
	Size() int
}

type WrapAnswerEnd_Terminate struct {
	Terminate *Terminate `protobuf:"bytes,1,opt,name=terminate,oneof" json:"terminate,omitempty"`
}
type WrapAnswerEnd_Answerend struct {
	Answerend *AnswerTestingEnded `protobuf:"bytes,2,opt,name=answerend,oneof" json:"answerend,omitempty"`
}

func (*WrapAnswerEnd_Terminate) isWrapAnswerEnd_M() {}
func (*WrapAnswerEnd_Answerend) isWrapAnswerEnd_M() {}

func (m *WrapAnswerEnd) GetM() isWrapAnswerEnd_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *WrapAnswerEnd) GetTerminate() *Terminate {
	if x, ok := m.GetM().(*WrapAnswerEnd_Terminate); ok {
		return x.Terminate
	}
	return nil
}

func (m *WrapAnswerEnd) GetAnswerend() *AnswerTestingEnded {
	if x, ok := m.GetM().(*WrapAnswerEnd_Answerend); ok {
		return x.Answerend
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WrapAnswerEnd) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WrapAnswerEnd_Terminate)(nil),
		(*WrapAnswerEnd_Answerend)(nil),
	}
}

type WrapRetryAccept struct {
	// Types that are valid to be assigned to M:
	//	*WrapRetryAccept_Terminate
	//	*WrapRetryAccept_Retry
	M                    isWrapRetryAccept_M `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WrapRetryAccept) Reset()         { *m = WrapRetryAccept{} }
func (m *WrapRetryAccept) String() string { return proto.CompactTextString(m) }
func (*WrapRetryAccept) ProtoMessage()    {}
func (*WrapRetryAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c94e6a4a939e96f, []int{11}
}
func (m *WrapRetryAccept) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WrapRetryAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WrapRetryAccept.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WrapRetryAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapRetryAccept.Merge(m, src)
}
func (m *WrapRetryAccept) XXX_Size() int {
	return m.Size()
}
func (m *WrapRetryAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapRetryAccept.DiscardUnknown(m)
}

var xxx_messageInfo_WrapRetryAccept proto.InternalMessageInfo

type isWrapRetryAccept_M interface {
	isWrapRetryAccept_M()
	MarshalTo([]byte) (int, error)
	Size() int
}

type WrapRetryAccept_Terminate struct {
	Terminate *Terminate `protobuf:"bytes,1,opt,name=terminate,oneof" json:"terminate,omitempty"`
}
type WrapRetryAccept_Retry struct {
	Retry *AcceptRetry `protobuf:"bytes,2,opt,name=retry,oneof" json:"retry,omitempty"`
}

func (*WrapRetryAccept_Terminate) isWrapRetryAccept_M() {}
func (*WrapRetryAccept_Retry) isWrapRetryAccept_M()     {}

func (m *WrapRetryAccept) GetM() isWrapRetryAccept_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *WrapRetryAccept) GetTerminate() *Terminate {
	if x, ok := m.GetM().(*WrapRetryAccept_Terminate); ok {
		return x.Terminate
	}
	return nil
}

func (m *WrapRetryAccept) GetRetry() *AcceptRetry {
	if x, ok := m.GetM().(*WrapRetryAccept_Retry); ok {
		return x.Retry
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WrapRetryAccept) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WrapRetryAccept_Terminate)(nil),
		(*WrapRetryAccept_Retry)(nil),
	}
}

func init() {
	proto.RegisterEnum("aside.pb.Reason", Reason_name, Reason_value)
	proto.RegisterType((*Hello)(nil), "aside.pb.Hello")
	proto.RegisterType((*StunServer)(nil), "aside.pb.StunServer")
	proto.RegisterType((*StunShare)(nil), "aside.pb.StunShare")
	proto.RegisterType((*SDP)(nil), "aside.pb.SDP")
	proto.RegisterType((*Candidate)(nil), "aside.pb.Candidate")
	proto.RegisterType((*GenerationEnded)(nil), "aside.pb.GenerationEnded")
	proto.RegisterType((*AnswerTestingEnded)(nil), "aside.pb.AnswerTestingEnded")
	proto.RegisterType((*AcceptRetry)(nil), "aside.pb.AcceptRetry")
	proto.RegisterType((*Terminate)(nil), "aside.pb.Terminate")
	proto.RegisterType((*WrapExchange)(nil), "aside.pb.WrapExchange")
	proto.RegisterType((*WrapAnswerEnd)(nil), "aside.pb.WrapAnswerEnd")
	proto.RegisterType((*WrapRetryAccept)(nil), "aside.pb.WrapRetryAccept")
}

func init() { proto.RegisterFile("aside.proto", fileDescriptor_6c94e6a4a939e96f) }

var fileDescriptor_6c94e6a4a939e96f = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xee, 0xb0, 0x50, 0xd9, 0xd3, 0x22, 0xcb, 0x80, 0x50, 0x0d, 0x12, 0x32, 0x31, 0xb1, 0x31,
	0x91, 0x0b, 0x88, 0x5e, 0x79, 0xb3, 0x94, 0x81, 0x12, 0x6d, 0x4b, 0x66, 0xb7, 0x70, 0xb9, 0x59,
	0xbb, 0x13, 0x58, 0xa5, 0xb3, 0xcd, 0xec, 0x2a, 0xea, 0x0b, 0x18, 0xef, 0xf4, 0x25, 0xf4, 0x55,
	0xfc, 0xb9, 0xf1, 0x11, 0x0c, 0x4f, 0x62, 0x66, 0x66, 0x7f, 0x28, 0xde, 0xe1, 0xd5, 0xcc, 0x39,
	0xdf, 0x77, 0xce, 0x7c, 0x73, 0xbe, 0x03, 0x8d, 0x30, 0x8d, 0x23, 0xbe, 0x35, 0x91, 0x49, 0x96,
	0xe0, 0xf9, 0x3c, 0x78, 0x49, 0xbe, 0x21, 0x98, 0xeb, 0xf2, 0xf3, 0xf3, 0x04, 0xaf, 0x83, 0x9d,
	0x9e, 0x85, 0x92, 0x7b, 0xd9, 0x1b, 0xd1, 0x42, 0x9b, 0x33, 0xed, 0x79, 0x56, 0x25, 0xf0, 0x03,
	0x58, 0xd0, 0xc1, 0x41, 0x92, 0x44, 0x9a, 0x31, 0xa3, 0x19, 0xd3, 0x49, 0x7c, 0x0f, 0xe6, 0x05,
	0xe7, 0x86, 0x60, 0x69, 0x42, 0x19, 0x2b, 0xec, 0x22, 0x14, 0x99, 0xc6, 0x66, 0x0d, 0x56, 0xc4,
	0x98, 0x40, 0x53, 0xdd, 0xcb, 0xe6, 0x73, 0x1a, 0x9f, 0xca, 0x91, 0x63, 0x00, 0x75, 0x7a, 0x5c,
	0xbe, 0xe5, 0x12, 0xaf, 0x42, 0x3d, 0x4a, 0xc6, 0x61, 0x6c, 0xa4, 0xda, 0x2c, 0x8f, 0x30, 0x86,
	0xd9, 0x49, 0x22, 0x33, 0x2d, 0x6f, 0x81, 0xe9, 0xbb, 0xfa, 0xd9, 0x6b, 0x91, 0x5c, 0x08, 0xd5,
	0x2a, 0x97, 0x55, 0x25, 0x48, 0x07, 0x6c, 0xdd, 0x57, 0x7d, 0x04, 0x3f, 0x85, 0x46, 0x5a, 0x3e,
	0x92, 0xb6, 0xd0, 0xa6, 0xd5, 0x6e, 0x6c, 0xaf, 0x6c, 0x15, 0xe3, 0xda, 0xaa, 0x14, 0xb0, 0xab,
	0x44, 0xb2, 0x06, 0x96, 0xb7, 0x77, 0x84, 0x1d, 0xb0, 0xd2, 0x68, 0x92, 0x4b, 0x52, 0x57, 0x72,
	0x1f, 0xec, 0x4e, 0x28, 0xa2, 0x38, 0x0a, 0x33, 0xae, 0xe0, 0x78, 0xc4, 0x0b, 0x38, 0x1e, 0x71,
	0xb2, 0x04, 0x8b, 0x07, 0x5c, 0x70, 0x19, 0x66, 0x71, 0x22, 0xa8, 0x88, 0x78, 0x44, 0x5e, 0x01,
	0x76, 0x45, 0x7a, 0xc1, 0xa5, 0xcf, 0xd3, 0x2c, 0x16, 0xa7, 0x3a, 0xab, 0xa6, 0x37, 0x4e, 0xa6,
	0xcc, 0x29, 0x63, 0x35, 0x3d, 0x75, 0xbf, 0x66, 0xcd, 0x54, 0x0e, 0xaf, 0xc0, 0x9c, 0xe4, 0x99,
	0x7c, 0x9f, 0xff, 0xdf, 0x04, 0xa4, 0x07, 0x0d, 0x77, 0x34, 0xe2, 0x93, 0x8c, 0xa9, 0xf0, 0x7f,
	0x1f, 0x21, 0x4f, 0xc0, 0xf6, 0xb9, 0x1c, 0xc7, 0x42, 0x7d, 0xb6, 0x0d, 0x75, 0xc9, 0xc3, 0x34,
	0x31, 0xad, 0x6e, 0x6f, 0x3b, 0xd5, 0x14, 0x99, 0xce, 0xb3, 0x1c, 0x27, 0x5f, 0x11, 0x34, 0x4f,
	0x64, 0x38, 0xa1, 0xef, 0x46, 0x67, 0xa1, 0x38, 0xe5, 0x78, 0x07, 0xec, 0xac, 0xe8, 0xd3, 0x42,
	0x9b, 0xa8, 0xdd, 0xd8, 0x5e, 0xae, 0xaa, 0xcb, 0x27, 0xba, 0x35, 0x56, 0xf1, 0xf0, 0x43, 0x33,
	0xdc, 0x99, 0xeb, 0xf4, 0x72, 0xfc, 0xdd, 0x9a, 0x9e, 0x39, 0xde, 0x81, 0xfa, 0x29, 0x17, 0x5c,
	0xa8, 0x5d, 0x50, 0xdc, 0xbb, 0x15, 0xf7, 0x9a, 0x17, 0xdd, 0x1a, 0xcb, 0xa9, 0xbb, 0x16, 0xa0,
	0x31, 0xf9, 0x88, 0x60, 0x41, 0x09, 0x35, 0xfe, 0x50, 0x11, 0xdd, 0x4c, 0xe9, 0x33, 0xb0, 0x43,
	0xdd, 0x41, 0x69, 0x30, 0x7a, 0xd7, 0xab, 0xa2, 0x7f, 0xcd, 0x57, 0xd5, 0x65, 0x81, 0x51, 0xf2,
	0x01, 0x16, 0x95, 0x10, 0x6d, 0x9b, 0x71, 0xf0, 0x66, 0x52, 0x1e, 0x17, 0x6b, 0x61, 0x64, 0xdc,
	0xb9, 0x22, 0xa3, 0xda, 0x8b, 0x6e, 0x2d, 0xdf, 0x17, 0xfd, 0xf6, 0xa3, 0x4f, 0x08, 0xea, 0xc6,
	0x41, 0xdc, 0x80, 0x5b, 0xde, 0xb0, 0xd3, 0xa1, 0x9e, 0xe7, 0x44, 0xb8, 0x05, 0xcb, 0xcc, 0xed,
	0x07, 0x83, 0xa1, 0x1f, 0x78, 0xfe, 0xb0, 0x1f, 0x78, 0x94, 0x1d, 0x53, 0xe6, 0xfc, 0x40, 0x78,
	0x0d, 0x70, 0x81, 0x0c, 0xf6, 0x03, 0x46, 0x7d, 0x76, 0x48, 0x3d, 0xe7, 0x27, 0xc2, 0x2b, 0xb0,
	0x78, 0xc4, 0x0e, 0x8f, 0x5d, 0x9f, 0x06, 0x87, 0x47, 0xba, 0xca, 0xf9, 0x85, 0xf0, 0x2a, 0x2c,
	0xf5, 0xdc, 0x17, 0xfb, 0x03, 0xd6, 0xa3, 0x7b, 0x41, 0x8f, 0x7a, 0x9e, 0x7b, 0x40, 0x9d, 0xcf,
	0x16, 0x5e, 0x82, 0xe6, 0xb0, 0xff, 0x7c, 0x70, 0xd2, 0x0f, 0x28, 0x63, 0x03, 0xe6, 0x7c, 0xb1,
	0x76, 0x9b, 0xdf, 0x2f, 0x37, 0xd0, 0xef, 0xcb, 0x0d, 0xf4, 0xe7, 0x72, 0x03, 0xfd, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0xc0, 0xbe, 0xfb, 0xe4, 0x04, 0x00, 0x00,
}

func (m *Hello) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Hello) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Hello) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.WantGoodStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("wantGoodStun")
	} else {
		i--
		if *m.WantGoodStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.WantStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("wantStun")
	} else {
		i--
		if *m.WantStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.NeedStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("needStun")
	} else {
		i--
		if *m.NeedStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ShareGoodStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("shareGoodStun")
	} else {
		i--
		if *m.ShareGoodStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.ShareStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("shareStun")
	} else {
		i--
		if *m.ShareStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StunServer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StunServer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StunServer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.KnownGood == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("knownGood")
	} else {
		i--
		if *m.KnownGood {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Port == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("port")
	} else {
		i = encodeVarintAside(dAtA, i, uint64(*m.Port))
		i--
		dAtA[i] = 0x10
	}
	if m.Domain == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("domain")
	} else {
		i -= len(*m.Domain)
		copy(dAtA[i:], *m.Domain)
		i = encodeVarintAside(dAtA, i, uint64(len(*m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StunShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StunShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StunShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.StunServers) > 0 {
		for iNdEx := len(m.StunServers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StunServers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAside(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SDP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SDP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SDP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Sdp == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("sdp")
	} else {
		i -= len(*m.Sdp)
		copy(dAtA[i:], *m.Sdp)
		i = encodeVarintAside(dAtA, i, uint64(len(*m.Sdp)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Candidate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Candidate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Candidate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Ice == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("ice")
	} else {
		i -= len(*m.Ice)
		copy(dAtA[i:], *m.Ice)
		i = encodeVarintAside(dAtA, i, uint64(len(*m.Ice)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerationEnded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerationEnded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerationEnded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *AnswerTestingEnded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AnswerTestingEnded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnswerTestingEnded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Retry == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("retry")
	} else {
		i--
		if *m.Retry {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MoreGoodStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreGoodStun")
	} else {
		i--
		if *m.MoreGoodStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MoreStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreStun")
	} else {
		i--
		if *m.MoreStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AcceptRetry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AcceptRetry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AcceptRetry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MoreGoodStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreGoodStun")
	} else {
		i--
		if *m.MoreGoodStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MoreStun == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreStun")
	} else {
		i--
		if *m.MoreStun {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Terminate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Terminate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Terminate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Reason == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("reason")
	} else {
		i = encodeVarintAside(dAtA, i, uint64(*m.Reason))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WrapExchange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WrapExchange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapExchange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.M != nil {
		{
			size := m.M.Size()
			i -= size
			if _, err := m.M.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *WrapExchange_Terminate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapExchange_Terminate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Terminate != nil {
		{
			size, err := m.Terminate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *WrapExchange_Ice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapExchange_Ice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Ice != nil {
		{
			size, err := m.Ice.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *WrapExchange_Genend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapExchange_Genend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Genend != nil {
		{
			size, err := m.Genend.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *WrapAnswerEnd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WrapAnswerEnd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapAnswerEnd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.M != nil {
		{
			size := m.M.Size()
			i -= size
			if _, err := m.M.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *WrapAnswerEnd_Terminate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapAnswerEnd_Terminate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Terminate != nil {
		{
			size, err := m.Terminate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *WrapAnswerEnd_Answerend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapAnswerEnd_Answerend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Answerend != nil {
		{
			size, err := m.Answerend.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *WrapRetryAccept) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WrapRetryAccept) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapRetryAccept) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.M != nil {
		{
			size := m.M.Size()
			i -= size
			if _, err := m.M.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *WrapRetryAccept_Terminate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapRetryAccept_Terminate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Terminate != nil {
		{
			size, err := m.Terminate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *WrapRetryAccept_Retry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrapRetryAccept_Retry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Retry != nil {
		{
			size, err := m.Retry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAside(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func encodeVarintAside(dAtA []byte, offset int, v uint64) int {
	offset -= sovAside(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Hello) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ShareStun != nil {
		n += 2
	}
	if m.ShareGoodStun != nil {
		n += 2
	}
	if m.NeedStun != nil {
		n += 2
	}
	if m.WantStun != nil {
		n += 2
	}
	if m.WantGoodStun != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StunServer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Domain != nil {
		l = len(*m.Domain)
		n += 1 + l + sovAside(uint64(l))
	}
	if m.Port != nil {
		n += 1 + sovAside(uint64(*m.Port))
	}
	if m.KnownGood != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StunShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StunServers) > 0 {
		for _, e := range m.StunServers {
			l = e.Size()
			n += 1 + l + sovAside(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SDP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sdp != nil {
		l = len(*m.Sdp)
		n += 1 + l + sovAside(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Candidate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ice != nil {
		l = len(*m.Ice)
		n += 1 + l + sovAside(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GenerationEnded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AnswerTestingEnded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MoreStun != nil {
		n += 2
	}
	if m.MoreGoodStun != nil {
		n += 2
	}
	if m.Retry != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AcceptRetry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MoreStun != nil {
		n += 2
	}
	if m.MoreGoodStun != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Terminate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reason != nil {
		n += 1 + sovAside(uint64(*m.Reason))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WrapExchange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.M != nil {
		n += m.M.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WrapExchange_Terminate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Terminate != nil {
		l = m.Terminate.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapExchange_Ice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ice != nil {
		l = m.Ice.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapExchange_Genend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Genend != nil {
		l = m.Genend.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapAnswerEnd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.M != nil {
		n += m.M.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WrapAnswerEnd_Terminate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Terminate != nil {
		l = m.Terminate.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapAnswerEnd_Answerend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Answerend != nil {
		l = m.Answerend.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapRetryAccept) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.M != nil {
		n += m.M.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WrapRetryAccept_Terminate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Terminate != nil {
		l = m.Terminate.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}
func (m *WrapRetryAccept_Retry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Retry != nil {
		l = m.Retry.Size()
		n += 1 + l + sovAside(uint64(l))
	}
	return n
}

func sovAside(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAside(x uint64) (n int) {
	return sovAside(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Hello) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Hello: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Hello: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ShareStun = &b
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareGoodStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ShareGoodStun = &b
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeedStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.NeedStun = &b
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WantStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.WantStun = &b
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WantGoodStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.WantGoodStun = &b
			hasFields[0] |= uint64(0x00000010)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("shareStun")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("shareGoodStun")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("needStun")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("wantStun")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("wantGoodStun")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StunServer) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StunServer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StunServer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Domain = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Port = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KnownGood", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.KnownGood = &b
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("domain")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("port")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("knownGood")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StunShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StunShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StunShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StunServers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StunServers = append(m.StunServers, &StunServer{})
			if err := m.StunServers[len(m.StunServers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SDP) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SDP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SDP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sdp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Sdp = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("sdp")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Candidate) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Candidate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Candidate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Ice = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ice")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerationEnded) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerationEnded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerationEnded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AnswerTestingEnded) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AnswerTestingEnded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AnswerTestingEnded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MoreStun = &b
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreGoodStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MoreGoodStun = &b
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retry", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Retry = &b
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreStun")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreGoodStun")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("retry")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AcceptRetry) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AcceptRetry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AcceptRetry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MoreStun = &b
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MoreGoodStun", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MoreGoodStun = &b
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreStun")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("moreGoodStun")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Terminate) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Terminate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Terminate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var v Reason
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= Reason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reason = &v
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("reason")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WrapExchange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WrapExchange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WrapExchange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Terminate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Terminate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapExchange_Terminate{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Candidate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapExchange_Ice{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Genend", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GenerationEnded{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapExchange_Genend{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WrapAnswerEnd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WrapAnswerEnd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WrapAnswerEnd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Terminate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Terminate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapAnswerEnd_Terminate{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answerend", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AnswerTestingEnded{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapAnswerEnd_Answerend{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WrapRetryAccept) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAside
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WrapRetryAccept: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WrapRetryAccept: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Terminate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Terminate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapRetryAccept_Terminate{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAside
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAside
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAside
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AcceptRetry{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.M = &WrapRetryAccept_Retry{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAside(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAside
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAside(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAside
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAside
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAside
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAside
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAside
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAside
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAside        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAside          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAside = fmt.Errorf("proto: unexpected end of group")
)
